### PR TITLE
use raw string prefix to prevent python warnings

### LINKED ISSUE #6: Invalid escape sequence detected
After updating HA to 2024.10.2 I found following warning in the logs:
```
2024-10-13 08:25:55.024 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.12/site-packages/pycrowipmodule/crow_defs.py:22: SyntaxWarning: invalid escape sequence '\d'
  'ZO(?P<data>\d+)': {'name': 'Zone Open', 'handler': 'zone_state_change', 'attr': 'open', 'status': True},

2024-10-13 08:25:55.025 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.12/site-packages/pycrowipmodule/crow_defs.py:23: SyntaxWarning: invalid escape sequence '\d'
  'ZC(?P<data>\d+)': {'name': 'Zone Closed', 'handler': 'zone_state_change','attr': 'open', 'status': False},

2024-10-13 08:25:55.025 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.12/site-packages/pycrowipmodule/crow_defs.py:24: SyntaxWarning: invalid escape sequence '\d'
  'ZA(?P<data>\d+)': {'name': 'Zone Alarm', 'handler': 'zone_state_change', 'attr': 'alarm', 'status': True},

2024-10-13 08:25:55.025 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.12/site-packages/pycrowipmodule/crow_defs.py:25: SyntaxWarning: invalid escape sequence '\d'
  'ZR(?P<data>\d+)': {'name': 'Zone Alarm Restore', 'handler': 'zone_state_change','attr': 'alarm', 'status': False},

2024-10-13 08:25:55.025 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.12/site-packages/pycrowipmodule/crow_defs.py:26: SyntaxWarning: invalid escape sequence '\d'
  'ZBY(?P<data>\d+)': {'name': 'Zone Bypass', 'handler': 'zone_state_change', 'attr': 'bypass', 'status': True},

2024-10-13 08:25:55.025 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.12/site-packages/pycrowipmodule/crow_defs.py:27: SyntaxWarning: invalid escape sequence '\d'
  'ZBYR(?P<data>\d+)': {'name': 'Zone Bypass Restore', 'handler': 'zone_state_change','attr': 'bypass', 'status': False},

2024-10-13 08:25:55.025 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.12/site-packages/pycrowipmodule/crow_defs.py:28: SyntaxWarning: invalid escape sequence '\d'
  'ZTA(?P<data>\d+)': {'name': 'Zone Tamper', 'handler': 'zone_state_change', 'attr': 'tamper', 'status': True},

2024-10-13 08:25:55.026 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.12/site-packages/pycrowipmodule/crow_defs.py:29: SyntaxWarning: invalid escape sequence '\d'
  'ZTR(?P<data>\d+)': {'name': 'Zone Tamper Restore', 'handler': 'zone_state_change','attr': 'tamper', 'status': False},

2024-10-13 08:25:55.026 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.12/site-packages/pycrowipmodule/crow_defs.py:44: SyntaxWarning: invalid escape sequence '\d'
  'OO(?P<data>\d+)': {'name': 'Output On', 'handler': 'output_state_change', 'attr': 'open', 'status': True},

2024-10-13 08:25:55.027 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.12/site-packages/pycrowipmodule/crow_defs.py:45: SyntaxWarning: invalid escape sequence '\d'
  'OC(?P<data>\d+)': {'name': 'Output Off', 'handler': 'output_state_change', 'attr': 'open', 'status': False},
```
Might have been there for a while as I don't regularly check the full log.

### PR DESCRIPTION
**Pull request by dan-s-github**
This should fix #6 updated version to 0.32b0 for now

### CODE REVIEW

**Comment by dan-s-github** [comment]
would like to get this deployed to PyPI before submitting PR to fix new HA deprecation warnings in 2024.11

**Comment by febalci** [comment]
Can you please change the new version from 0.32b0 to 0.32 in the setup.py; since 0.31b0 was only meant to be created as a beta version. After that i can merge and publish on pypi.

**Comment by dan-s-github** [comment]
done

**Comment by dan-s-github** [comment]
version has been updated, did you find any issue?

**Comment by febalci** [comment]
Added to pypi. Can you try it with 0.32? In custom_components/croipmodule/manifest.json file,  "requirements": ["pycrowipmodule ==0.31b0"], line to "requirements": ["pycrowipmodule ==0.32"],

I compiled it under osx arm64, ashoulds not be any problem but who knows? Thanks a lot.

**Pull request merged**
